DELETE http://localhost:3003/api/posts/5de1b34df1fe6a470c81b3d7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvcmlzc2plcmpvbWsiLCJpZCI6IjVkZTFiMGM4ZjFmZTZhNDcwYzgxYjNkNiIsImlhdCI6MTU3NTEyMTk4NX0.MGdahypTLqBusdxajHENn3XrYd338l4R6jfvozPlxBk

