POST http://localhost:3003/api/posts/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvcmlzc2plcmpvbWsiLCJpZCI6IjVkZTFiMGM4ZjFmZTZhNDcwYzgxYjNkNiIsImlhdCI6MTU3NTEyMTMzMX0.SP9hEVeib4UPLf25mUb_b_sSu54DUMFlsdIxK0XTZ_w

{
  "title": "Minun elamam kerta1!!..,,",
  "text": "lorem ipsum....................................askdfnjmoaiknfmoiasenmfoaw",
  "likes": 0
}